### ISSUE TITLE
values.yaml: reserved words

### ISSUE THREAD

**Issue by timfeirg** [timfeirg/lain-cli#3]
防呆设计, 将一系列单词列为保留字, 不允许开发者在 values 用作命名. 起因是有同事抄写错误, 没注意缩进, 导致写出这样一块东西:

```yaml
deployments:
  cronjobs:
    commands: ...
```

写完这坨东西以后, 还不明白为啥没有部署出 cronjobs.

因此实现的时候, 很可能是将所有 marshmallow schema 字段都列为保留字, 均不允许作为自定义命名.
